#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=bkrosenz@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=0-22:59:00
#SBATCH --account=r01149
#SBATCH --cpus-per-gpu=10
#SBATCH --gpus-per-node=1
#SBATCH --partition=hopper
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH -o attn_jc_%j.txt

######  Module commands #####
module load conda cudatoolkit/12.6

######  Job commands go below this line #####
. deactivate
conda activate /N/project/phyloML/app/Quartz/miniconda3/envs/torch

cd /N/project/phyloML/phylo-DNN
# deeper 

VALDIR=/N/project/phyloML/data/phyloDNN/val/dna/
# CONFIG_DIR=/N/project/phyloML/trained_models/configurations/equivariant
ROOT_DIR=/N/project/phyloML/data/phyloDNN/train/dna/
CONFIG_DIR=/N/project/phyloML/trained_models/configurations/attn
CHECKPOINT_DIR=/N/project/phyloML/trained_models/final #attn
EPOCHS=100
SEQDIR=jc

# for model in seq1 seq1pair1 seq4 seq3pair1;
# do
#     python train_and_test.py --rootdir $ROOT_DIR \
#         --seqdir $SEQDIR \
#         --config $CONFIG_DIR/$model.config \
#         --checkpoint_dir $CHECKPOINT_DIR/$SEQDIR/$model/ \
#         --valdir $VALDIR \
#         --workers 10 --epochs $EPOCHS --batch_size 1024 --amp;
# done


for model in s3cr_p3r_mae row_only s3p3_mae seq row_only_4  seq_row_only seq_col_only col_only original  row_s2p1_l21  s3p3_h64_lse s3p3_lse
do
python train_and_test.py --rootdir $ROOT_DIR  \
      --seqdir jc  \
      --config $CONFIG_DIR/$model.config  \
      --checkpoint_dir $CHECKPOINT_DIR/jc/$model/   \
      --valdir $VALDIR  \
      --workers 10 --epochs $EPOCHS \
      --batch_size 8 --early_stopping; #  --amp
done
