#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=bkrosenz@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=0-22:59:00
#SBATCH --account=r01149
#SBATCH --cpus-per-gpu=10
#SBATCH --gpus-per-node=1
#SBATCH --partition=hopper
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH -o equiv_jc_d32_%j.txt

######  Module commands #####
module load conda

######  Job commands go below this line #####
. deactivate
conda deactivate
conda activate /N/project/phyloML/app/Quartz/miniconda3/envs/torch

cd /N/project/phyloML/phylo-DNN
# deeper 

VALDIR=/N/project/phyloML/data/phyloDNN/val/prot/
ROOT_DIR=/N/project/phyloML/data/phyloDNN/train/prot/

CONFIG_DIR=/N/project/phyloML/trained_models/configurations/small/h32/mae
CHECKPOINT_DIR=/N/project/phyloML/trained_models/final
EPOCHS=200
SEQDIR=lg_gc

for model in seq1b_f256x4_h4 seq6b_f256x4_h4 seq1b_f64_h4 seq1_f64x2 seq1_f64 seq1_f64_h4 seq1b_f64_i7_h4 seq1_f64_l21 seq1b_f64_l21 pair1b_f64_h4 seq1b_f64_h4_i7_l21
do

    python train_and_test.py --rootdir $ROOT_DIR \
    --seqdir $SEQDIR \
    --config $CONFIG_DIR/$model.config \
    --checkpoint_dir $CHECKPOINT_DIR/${SEQDIR}/$model/ \
    --valdir $VALDIR \
    --workers 10 --early_stopping --epochs $EPOCHS
    #  --batch_size 2048; 
done

